name = "smm"
description = "Stephe's Music Manager"
version = "1.0.0"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

project-files = ["build/smm_alire.gpr"]

#  We use ".exe" extension even on non-Windows, to simplify the makefiles.
executables = ["smm.exe"]

[[depends-on]]
# ada_web_server
aws = "^23.0.0"
gnatcoll_iconv = "^23.0.0"
gnatcoll_sqlite = "^23.0.0"
stephes_ada_library = "~3.7.2"

# We use Ada 2022 syntax, so need the -gnat2022 switch; introduced in gnat FSF 11, Community 2021. 
gnat = "(>=11 & <2000) | >=2021"

[[pins]]
stephes_ada_library = { path='../org.stephe_leake.sal' }
