name = "smm"
description = "Stephe's Music Manager"
version = "1.0.0"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

project-files = ["build/smm_alire.gpr"]

[[depends-on]]
# I tried to put tests in a separate crate, but "alr build --
# test_one_harness.adb" tried to build that file in the smm crate.
# So this crate holds the main application and the tests.
aunit = "^25.0.0"
aunit_ext = "1.0.0"

# 'gnatcoll' includes json
gnatcoll        = "^23.0.0"
gnatcoll_iconv  = "^23.0.0"
gnatcoll_sqlite = "^23.0.0"

stephes_ada_library = "~3.7.2"

# http client library simpler than AWS
utilada_curl = "^2.8.0"

# We use Ada 2022 syntax, so need the -gnat2022 switch; introduced in gnat FSF 11, Community 2021. 
gnat = "(>=11 & <2000) | >=2021"

[[pins]]
aunit_ext = { path='../org.stephe_leake.aunit_ext' }
stephes_ada_library = { path='../org.stephe_leake.sal' }
