CREATE TABLE IF NOT EXISTS Author
(ID     INTEGER UNSIGNED AUTO_INCREMENT,
 First  VARCHAR(20),
 Middle VARCHAR(20),
 Last   VARCHAR(20),
 PRIMARY KEY ID (ID),
 UNIQUE INDEX `Last Name` (Last, First, Middle),
 UNIQUE INDEX Name (First, Middle, Last));

CREATE TABLE IF NOT EXISTS Collection
(ID     INTEGER UNSIGNED AUTO_INCREMENT,
 Name   VARCHAR(50),
 Editor INTEGER UNSIGNED,
 Year   SMALLINT UNSIGNED,
 PRIMARY KEY ID (ID),
 UNIQUE INDEX Name (Name));

CREATE TABLE IF NOT EXISTS Series
(ID     INTEGER UNSIGNED AUTO_INCREMENT,
 Title  VARCHAR(50),
 Author INTEGER UNSIGNED,
 PRIMARY KEY ID (ID),
 UNIQUE INDEX Title (Title));

CREATE TABLE IF NOT EXISTS Title
(ID     INTEGER UNSIGNED AUTO_INCREMENT,
 Title  VARCHAR(50),
 Year   SMALLINT UNSIGNED,
 Comment VARCHAR(50),
 Rating TINYINT UNSIGNED,
 PRIMARY KEY ID (ID),
 UNIQUE INDEX `Title Year` (Title,Year));

CREATE TABLE IF NOT EXISTS AuthorTitle
(Author INTEGER UNSIGNED,
 Title  INTEGER UNSIGNED,
 INDEX Author (Author),
 INDEX Title (Title));

CREATE TABLE IF NOT EXISTS SeriesTitle
(Series INTEGER UNSIGNED,
 Title  INTEGER UNSIGNED,
 INDEX Series (Series),
 INDEX Title (Title));

CREATE TABLE IF NOT EXISTS CollectionTitle
(Collection INTEGER UNSIGNED,
 Title  INTEGER UNSIGNED,
 INDEX Collection (Collection),
 INDEX Title (Title));

-- end of file
